controller:
  ingressClass: nginx-ingress-public
  containerPort:
    http: 80
    https: 443
    special: 8000
  config:
    ssl-redirect: "false" # we use `special` port to control ssl redirection
    server-snippet: |
      listen 8000;
      if ( $server_port = 80 ) {
         return 308 https://$host$request_uri;
      }
  # publishService required to Allow ELB Alias for DNS registration w/ external-dns
  kind: DaemonSet
  publishService:
    enabled: true
  service:
    # AWS Annotations for LoadBalaner with Certificate ARN
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "	arn:aws:acm:us-west-2:499898277306:certificate/832895f4-e8b9-41a6-912a-a00c47f6b367"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    # TLS (https) terminated at ELB, so internal endpoint is 'http'
    targetPorts:
      http: http
      https: special
