secrets:
    azblue-bcr-automation-secrets:
      key: elastic_auth.json

namespaces:
  devops-utils:
    quota_pods: "30"
    quota_mem: "5Gi"
    quota_cpu: "6"    
  prod-bridge:
    quota_pods: "30"
    quota_mem: "4096Mi"
    quota_cpu: "4"
  prod-bcbs:
    quota_pods: "16"
    quota_mem: 4096Mi
    quota_cpu: "4"
